<?php
// $Id$
/**
 * @file
 * Install/Updates for cd_civicrm.
 */

/**
 * Implementation of hook_uninstall().
 *
 * @return none
 */
function cd_civicrm_uninstall() {
  // Remove variables.
  variable_del('cd_civicrm_cd');
  variable_del('cd_civicrm_cd_override');
  variable_del('cd_civicrm_custom_field_cd');
  variable_del('cd_civicrm_custom_field_cd_override');
  variable_del('cd_civicrm_geocoding_off');
  variable_del('cd_civicrm_crypt_iv');
}

/**
 * Implementation of hook_requriements().
 */
function cd_civicrm_requirements($phase) {
  global $db_prefix;
  $requirements = array();
  if ($phase == 'runtime') {

    // Raise an error if we do not have prefixes for all the CiviCRM tables.
    $civicrm_tables = array(
      'civicrm_custom_field',
      'civicrm_contact',
      'civicrm_address',
      'civicrm_custom_group',
      'civicrm_uf_match',
      variable_get('cd_civicrm_custom_table', ''),
    );
    $error_tables = array();
    foreach ($civicrm_tables as $table) {
      if ($table && !isset($db_prefix[$table])) {
        $error_tables[] = $table;
      }
    }
    $requirements['cd_civicrm_db'] = array(
      'title' => 'CiviCRM Congressional District',
      'description' => t('In %settings $db_prefix must be an array and you must have prefixes ' .
        'for the following tables: %tables.  See the <a href="!url">CiviCRM Views Integration</a> ' .
        'for more info.',
        array(
        '%tables' => implode(', ', $civicrm_tables),
        '!url' => url('civicrm/admin/setting/uf'),
        '%settings' => conf_path() . '/settings.php',
      )),
      'severity' => $error_tables ? REQUIREMENT_ERROR : REQUIREMENT_OK,
      'value' => t('settings.php DB Prefix'),
    );
    if ($error_tables) {
      $requirements['cd_civicrm_db']['description'] .= t(
        'Prefixes do not exist for the following tables: %tables.', array(
        '%tables' => implode(', ', $error_tables),
      ));
    }

    // If we already have an error, don't bother continuing, it will only confuse the admin.
    // They need to get the above sorted out before they can do anything.
    if ($error_tables) {
      return $requirements;
    }

    // Raise an error if a the module has not been setup.
    if (
      !variable_get('cd_civicrm_cd', '') ||
      !variable_get('cd_civicrm_cd_override', '')
    ) {
      $requirements['cd_civicrm_fields'] = array(
        'title' => 'CiviCRM Congressional District fields',
        'description' => t('You have not <a href="!url">chosen storage fields</a> for CiviCRM data.'
          , array('!url' => url('admin/settings/cd_sunlight/cd_civicrm'))),
        'severity' => REQUIREMENT_ERROR,
        'value' => t('Not configured'),
      );
    }

    // Report the number of records in the batch geocoding queue.
    if (variable_get('cd_civicrm_geocoding_off', FALSE)) {
      $count = db_result(db_query('SELECT COUNT(*) FROM {civicrm_address}
        WHERE geo_code_1 IS NULL
          AND country_id IS NOT NULL
          AND state_province_id IS NOT NULL'));
      $requirements['cd_civicrm_geocode_count'] = array(
        'title' => 'CiviCRM Congressional District contact geocoding',
        'value' => t('There are roughly !count contacts in the queue to be geocoded.',
          array('!count' => $count)),
        'count' => $count,
        'severity' => REQUIREMENT_INFO,
      );
    }

  }
  return $requirements;
}